# Generated by Django 2.2.3 on 2019-07-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mammadovsapp', '0004_auto_20190706_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
