# Generated by Django 2.2.3 on 2019-07-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mammadovsapp', '0005_auto_20190706_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
