# Generated by Django 2.2.3 on 2019-07-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mammadovsapp', '0009_auto_20190715_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
