# Generated by Django 2.2.3 on 2019-07-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mammadovsapp', '0010_auto_20190720_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image_url',
            new_name='image',
        ),
    ]
