# Generated by Django 2.2.4 on 2019-08-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mammadovsapp', '0013_auto_20190823_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(max_length=2000),
        ),
    ]
